from __future__ import annotations

from .models import Concept


def get_seed_concepts(course_name: str, template_mode: str = "generic") -> list[Concept]:
    mode = _normalize_template_mode(template_mode)

    if mode == "generic":
        return []

    if mode == "linear-algebra":
        is_linear_algebra = True
    elif mode == "auto":
        lowered = course_name.lower()
        is_linear_algebra = any(
            keyword in lowered
            for keyword in (
                "linear algebra",
                "lin alg",
                "matrix",
                "\u7dda\u6027\u4ee3\u6578",
                "\u7ebf\u6027\u4ee3\u6570",
            )
        )
    else:
        return []

    if not is_linear_algebra:
        return []

    return _linear_algebra_seed_concepts()


def _normalize_template_mode(template_mode: str) -> str:
    lowered = (template_mode or "").strip().lower()
    alias_map = {
        "": "generic",
        "none": "generic",
        "generic": "generic",
        "general": "generic",
        "auto": "auto",
        "linear-algebra": "linear-algebra",
        "linear_algebra": "linear-algebra",
        "linear algebra": "linear-algebra",
        "\u7dda\u6027\u4ee3\u6578": "linear-algebra",
        "\u7ebf\u6027\u4ee3\u6570": "linear-algebra",
    }
    return alias_map.get(lowered, "generic")


def _linear_algebra_seed_concepts() -> list[Concept]:
    return [
        Concept(
            id="la-vector-space",
            name="Vector Space",
            chapter="Ch1 Foundations",
            description="A set with vector addition and scalar multiplication satisfying axioms.",
            prerequisites=[],
        ),
        Concept(
            id="la-linear-combination",
            name="Linear Combination",
            chapter="Ch1 Foundations",
            description="Represents a vector as weighted sum of other vectors.",
            prerequisites=["Vector Space"],
        ),
        Concept(
            id="la-span",
            name="Span",
            chapter="Ch1 Foundations",
            description="The set of all linear combinations generated by a vector set.",
            prerequisites=["Linear Combination"],
        ),
        Concept(
            id="la-linear-independence",
            name="Linear Independence",
            chapter="Ch1 Foundations",
            description="No vector in the set can be represented by others.",
            prerequisites=["Span"],
        ),
        Concept(
            id="la-basis",
            name="Basis",
            chapter="Ch2 Subspaces",
            description="A linearly independent spanning set of a vector space.",
            prerequisites=["Linear Independence", "Span"],
        ),
        Concept(
            id="la-dimension",
            name="Dimension",
            chapter="Ch2 Subspaces",
            description="The number of vectors in any basis of a vector space.",
            prerequisites=["Basis"],
        ),
        Concept(
            id="la-matrix-ops",
            name="Matrix and Elementary Operations",
            chapter="Ch3 Matrices",
            description="Matrix representation and elementary row operations for solving systems.",
            prerequisites=["Vector Space"],
        ),
        Concept(
            id="la-row-reduction",
            name="Row Reduction",
            chapter="Ch3 Matrices",
            description="Transforming a matrix to echelon forms to reveal structure.",
            prerequisites=["Matrix and Elementary Operations"],
        ),
        Concept(
            id="la-rank",
            name="Rank",
            chapter="Ch3 Matrices",
            description="The dimension of column space or row space.",
            prerequisites=["Row Reduction", "Dimension"],
        ),
        Concept(
            id="la-null-space",
            name="Null Space",
            chapter="Ch4 Spaces",
            description="All solutions of homogeneous equation Ax = 0.",
            prerequisites=["Row Reduction"],
        ),
        Concept(
            id="la-column-space",
            name="Column Space",
            chapter="Ch4 Spaces",
            description="Subspace spanned by the columns of a matrix.",
            prerequisites=["Row Reduction"],
        ),
        Concept(
            id="la-linear-transform",
            name="Linear Transformation",
            chapter="Ch5 Transformations",
            description="A map preserving vector addition and scalar multiplication.",
            prerequisites=["Vector Space", "Matrix and Elementary Operations"],
        ),
        Concept(
            id="la-determinant",
            name="Determinant",
            chapter="Ch6 Determinants",
            description="A scalar indicating volume scaling and invertibility clues.",
            prerequisites=["Row Reduction"],
        ),
        Concept(
            id="la-invertibility",
            name="Invertibility",
            chapter="Ch6 Determinants",
            description="Conditions under which matrix inverse exists.",
            prerequisites=["Rank", "Determinant"],
        ),
        Concept(
            id="la-eigen",
            name="Eigenvalue and Eigenvector",
            chapter="Ch7 Eigen",
            description="Special vectors scaled by transformation matrices.",
            prerequisites=["Linear Transformation"],
        ),
        Concept(
            id="la-diagonalization",
            name="Diagonalization",
            chapter="Ch7 Eigen",
            description="Factorization into PDP^-1 when enough eigenvectors exist.",
            prerequisites=["Eigenvalue and Eigenvector", "Invertibility"],
        ),
    ]
